config-version: 2

name: 'zendesk_source'
version: '0.6.1'


require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  zendesk_source:
    materialized: view
    catalog: intermediate
    +schema: staging_zendesk
    tmp:
      materialized: view

vars:
  zendesk_source:
    group: "{{ source('bronze', 'zendesk_group') }}"
    brand: "{{ source('bronze', 'zendesk_brand') }}"
    domain_name: "{{ source('bronze', 'zendesk_domain_name') }}"
    organization_tag: "{{ source('bronze', 'zendesk_organization_tag') }}"
    organization: "{{ source('bronze', 'zendesk_organization') }}"
    schedule: "{{ source('bronze', 'zendesk_schedule') }}"
    satisfaction_rating: "{{ source('bronze', 'zendesk_satisfaction_rating') }}"
    ticket: "{{ source('bronze', 'zendesk_ticket') }}"
    ticket_form_history: "{{ source('bronze', 'zendesk_ticket_form_history') }}"
    ticket_comment: "{{ source('bronze', 'zendesk_ticket_comment') }}"
    ticket_field_history: "{{ source('bronze', 'zendesk_ticket_field_history') }}"
    ticket_schedule: "{{ source('bronze', 'zendesk_ticket_schedule') }}"
    ticket_tag: "{{ source('bronze', 'zendesk_ticket_tag') }}"
    user_tag: "{{ source('bronze', 'zendesk_user_tag') }}"
    user: "{{ source('bronze', 'zendesk_user') }}"
    time_zone: "{{ source('bronze', 'zendesk_time_zone') }}"
    daylight_time: "{{ source('bronze', 'zendesk_daylight_time') }}"
    zendesk_schema: bronze
    using_schedules: false 
    zendesk__ticket_passthrough_columns: [
    'custom_received_at_noreply_'
    ,'custom_ticket_type'
    ,'custom_about'
    ,'custom_total_time_spent_sec_'
    , 'custom_qc_provided_accurate_information_asked_clarifying_question'
    , 'custom_qc_used_connection_empathy_statement_s_'
    , 'custom_qc_cobrowsed_with_a_customer'
    , 'custom_qc_validated_the_customer'
    , 'custom_qc_had_a_winback'
    , 'custom_qc_was_courteous_throughout_the_interaction'
    , 'custom_qc_accuracy_comments'
    , 'custom_qc_properly_documented_the_ticket'
    , 'custom_qc_provided_tip_best_practices'
    , 'custom_qc_followed_procedures'
    , 'custom_qc_connection_comments'
    , 'custom_qc_offered_opportunity_for_follow_up_questions'
    , 'custom_qc_has_been_qc_d'
    , 'custom_qc_included_product_penetration_statement'
    , 'custom_qc_security_comments'
    , 'custom_queue'
    , 'custom_dispute_status'
    , 'custom_dispute_type'
    , 'custom_dispute_qc_was_a_final_dispute_resolution_letter_sent_was_the_pvc_clawback_letter_sent_'
    , 'custom_dispute_qc_was_a_marqeta_chargeback_credit_applied_'
    , 'custom_dispute_qc_was_a_marqeta_chargeback_response_received_'
    , 'custom_dispute_qc_was_a_pvc_letter_sent_'
    , 'custom_dispute_qc_was_pvc_issued_'
    , 'custom_dispute_qc_was_pvc_issued_within_10_days_'
    , 'custom_dispute_qc_was_pvc_reversed_within_5_days_'
    , 'custom_dispute_qc_was_this_correctly_classified_as_reg_e_vs_non_reg_e_'
    , 'custom_dispute_qc_were_the_disputed_transactions_already_disputed_on_another_claim_'
    , 'custom_dispute_qc_when_was_the_chargeback_credit_applied_' 
    , 'custom_dispute_qc_when_was_the_marqeta_chargeback_submitted_'
    , 'custom_reason_why_was_pvc_not_issued_within_10_days_'
    , 'custom_reason_why_wasn_t_a_marqeta_chargeback_credit_applied_'
    , 'custom_date_of_issue'
    , 'custom_provide_an_explanation_for_the_issue_marqeta_chargeback_response_not_received_'
    , 'custom_reason_for_dispute'
    , 'custom_contact_verification_status'
    , 'custom_contact_id'
    , 'custom_potential_ato'
    , 'custom_agent_selected_dispute_type'
    , 'custom_reason_for_risk_review'
    , 'custom_ur_priority'
    , 'custom_customer_complaint_channel_c_'
    , 'custom_potential_compliance_complaint_c_'
    , 'custom_complaint_sub_category_c_'
    , 'custom_actions_already_taken_c_'
    , 'custom_complaint_resolution_c_'
    , 'custom_goodwill_requested_but_not_approved_c_'
    , 'custom_escalated_complaint_type_c_'
    , 'custom_bank_error_goodwill_c_'
    , 'custom_complaint_narrative_c_'
    , 'custom_complaint_source_c_'
    , 'custom_complaint_status_c_'
    , 'custom_complaint_closed_status_c_'
    , 'custom_complaint_received_date_c_'
    , 'custom_desired_resolution_c_'
    , 'custom_associated_ticket_c_'
    , 'custom_compliant_approval_button_to_approve_extension_c_'
    , 'custom_complaint_root_cause_c_'
    , 'custom_reason_for_exceeding_sla_c_'
    , 'custom_goodwill_not_approved_detail_c_'
    , 'custom_complaint_product_c_'
    , 'custom_is_this_a_customer_complaint_c_'
    , 'custom_complaint_agents_only_c_'
    , 'custom_complaint_category_c_'
    , 'custom_no_bank_error_goodwill_c_'
    , 'custom_complaint_resolved_date_c_'
    , 'custom_contact_driver'
    
    ]
